import * as React from 'react'

import { Button } from '@/components/ui/button'
import { parsePdfMetadataKeywords } from '@/lib/pdfMetadata'
import type { SessionNotesFormValues } from '@/schemas/sessionNotesSchema'

const ERROR_MESSAGES: Record<string, string> = {
  missing: "This PDF doesn't look like one generated by this app, so there's nothing to import.",
  corrupt: "This PDF doesn't look like one generated by this app, so there's nothing to import.",
  'wrong-app': "This PDF doesn't look like one generated by this app, so there's nothing to import.",
  'unsupported-version': 'This PDF was created by a newer version of this app and can’t be imported here.',
  'invalid-data': "This PDF's embedded data looks damaged and couldn't be read safely.",
  'read-failed': "Couldn't read this file — make sure it's a PDF generated by this app.",
}

type ImportPdfButtonProps = {
  onImport: (values: SessionNotesFormValues) => void
}

export function ImportPdfButton({ onImport }: ImportPdfButtonProps) {
  const inputRef = React.useRef<HTMLInputElement | null>(null)
  const [status, setStatus] = React.useState<'idle' | 'loading' | 'error'>('idle')
  const [errorMessage, setErrorMessage] = React.useState('')

  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    event.target.value = ''
    if (!file) return

    setStatus('loading')
    try {
      // Lazy-loaded: pdf-lib is only needed for this one feature.
      const [{ PDFDocument }, bytes] = await Promise.all([import('pdf-lib'), file.arrayBuffer()])
      const pdfDoc = await PDFDocument.load(bytes)
      const result = parsePdfMetadataKeywords(pdfDoc.getKeywords())

      if (!result.ok) {
        setStatus('error')
        setErrorMessage(ERROR_MESSAGES[result.reason])
        return
      }

      onImport(result.data)
      setStatus('idle')
    } catch {
      setStatus('error')
      setErrorMessage(ERROR_MESSAGES['read-failed'])
    }
  }

  return (
    <div className="rounded-lg border border-dashed p-4">
      <p className="text-sm font-medium">Editing a previous session?</p>
      <p className="text-sm text-muted-foreground">
        Upload its PDF to prefill this form — nothing is uploaded anywhere, it's read in your
        browser.
      </p>
      <div className="mt-3 flex items-center gap-3">
        <Button
          type="button"
          variant="outline"
          size="sm"
          disabled={status === 'loading'}
          onClick={() => inputRef.current?.click()}
        >
          {status === 'loading' ? 'Reading PDF…' : 'Upload PDF'}
        </Button>
        <input
          ref={inputRef}
          type="file"
          accept="application/pdf"
          className="hidden"
          onChange={handleFileChange}
        />
        {status === 'error' && <p className="text-sm text-destructive">{errorMessage}</p>}
      </div>
    </div>
  )
}
